version: '3.8'

services:
  restart-qbittorrent-amule:
    image: itaiber2000/restart-qbittorent-amule:1.2.0
    container_name: restart-p2p-containers
    restart: unless-stopped
    network_mode: none # it doesn't need internet connectivity, it's more secure this way
    environment:
      - TZ=Asia/Jerusalem
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # normally, you'd have gluetun and qibtorrent services here too
    # depends_on:
    #   gluetun:
    #     condition: service_healthy
    #   qbittorrent:
    #     condition: service_started
    #   amule:
    #     condition: service_started
